services:
  olist-dashboard:
    build:
      context: .
    image: angelfelizr/olist-dashboard:0.0.1
    container_name: olist-dashboard
    ports:
      - "2225:22"
    volumes:
      - .:/root/olist-logistics-dashboard
